# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1029, 716)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.function_label = QtWidgets.QLabel(self.centralwidget)
        self.function_label.setGeometry(QtCore.QRect(200, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.function_label.setFont(font)
        self.function_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.function_label.setObjectName("function_label")
        self.a2_input = QtWidgets.QLineEdit(self.centralwidget)
        self.a2_input.setGeometry(QtCore.QRect(390, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.a2_input.setFont(font)
        self.a2_input.setText("")
        self.a2_input.setObjectName("a2_input")
        self.function_name_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.function_name_edit.setEnabled(False)
        self.function_name_edit.setGeometry(QtCore.QRect(320, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.function_name_edit.setFont(font)
        self.function_name_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.function_name_edit.setProperty("clearButtonEnabled", False)
        self.function_name_edit.setObjectName("function_name_edit")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 70, 351, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.population_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.population_label.setFont(font)
        self.population_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.population_label.setObjectName("population_label")
        self.gridLayout.addWidget(self.population_label, 0, 0, 1, 1)
        self.population_label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.population_label_3.setFont(font)
        self.population_label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.population_label_3.setObjectName("population_label_3")
        self.gridLayout.addWidget(self.population_label_3, 2, 0, 1, 1)
        self.population_label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.population_label_2.setFont(font)
        self.population_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.population_label_2.setObjectName("population_label_2")
        self.gridLayout.addWidget(self.population_label_2, 1, 0, 1, 1)
        self.pop_size = QtWidgets.QSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pop_size.setFont(font)
        self.pop_size.setAccelerated(True)
        self.pop_size.setMaximum(1000)
        self.pop_size.setProperty("value", 50)
        self.pop_size.setObjectName("pop_size")
        self.gridLayout.addWidget(self.pop_size, 0, 1, 1, 1)
        self.cross_prob = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cross_prob.setFont(font)
        self.cross_prob.setAccelerated(True)
        self.cross_prob.setMaximum(1.0)
        self.cross_prob.setSingleStep(0.01)
        self.cross_prob.setProperty("value", 1.0)
        self.cross_prob.setObjectName("cross_prob")
        self.gridLayout.addWidget(self.cross_prob, 1, 1, 1, 1)
        self.mutate_prob = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mutate_prob.setFont(font)
        self.mutate_prob.setAccelerated(True)
        self.mutate_prob.setDecimals(3)
        self.mutate_prob.setMaximum(1.0)
        self.mutate_prob.setSingleStep(0.001)
        self.mutate_prob.setProperty("value", 0.01)
        self.mutate_prob.setObjectName("mutate_prob")
        self.gridLayout.addWidget(self.mutate_prob, 2, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(400, 60, 171, 161))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.next_step_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.next_step_btn.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.next_step_btn.setFont(font)
        self.next_step_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_step_btn.setStyleSheet("padding:5px;")
        self.next_step_btn.setObjectName("next_step_btn")
        self.gridLayout_2.addWidget(self.next_step_btn, 1, 0, 1, 1)
        self.start_auto_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.start_auto_btn.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.start_auto_btn.setFont(font)
        self.start_auto_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_auto_btn.setStyleSheet("padding: 5px;")
        self.start_auto_btn.setObjectName("start_auto_btn")
        self.gridLayout_2.addWidget(self.start_auto_btn, 0, 0, 1, 1)
        self.canvas = QtWidgets.QGraphicsView(self.centralwidget)
        self.canvas.setGeometry(QtCore.QRect(710, 10, 21, 21))
        self.canvas.setObjectName("canvas")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 250, 451, 311))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(490, 250, 501, 311))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setGeometry(QtCore.QRect(450, 20, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.a1_input = QtWidgets.QLineEdit(self.centralwidget)
        self.a1_input.setGeometry(QtCore.QRect(520, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.a1_input.setFont(font)
        self.a1_input.setText("")
        self.a1_input.setObjectName("a1_input")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setGeometry(QtCore.QRect(580, 20, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.a0_input = QtWidgets.QLineEdit(self.centralwidget)
        self.a0_input.setGeometry(QtCore.QRect(640, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.a0_input.setFont(font)
        self.a0_input.setText("")
        self.a0_input.setObjectName("a0_input")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(500, 20, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(620, 20, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 180, 351, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.apply_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.apply_btn.setFont(font)
        self.apply_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.apply_btn.setStyleSheet("padding: 5px;")
        self.apply_btn.setObjectName("apply_btn")
        self.horizontalLayout.addWidget(self.apply_btn)
        self.clear_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.clear_btn.setFont(font)
        self.clear_btn.setStyleSheet("padding: 5px;")
        self.clear_btn.setObjectName("clear_btn")
        self.horizontalLayout.addWidget(self.clear_btn)
        self.reset_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.reset_btn.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.reset_btn.setFont(font)
        self.reset_btn.setStyleSheet("padding:5px;")
        self.reset_btn.setObjectName("reset_btn")
        self.horizontalLayout.addWidget(self.reset_btn)
        self.log_label = QtWidgets.QLabel(self.centralwidget)
        self.log_label.setGeometry(QtCore.QRect(580, 70, 171, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.log_label.setFont(font)
        self.log_label.setStyleSheet("")
        self.log_label.setObjectName("log_label")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(540, 570, 446, 33))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.max_check = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.max_check.setFont(font)
        self.max_check.setChecked(True)
        self.max_check.setObjectName("max_check")
        self.horizontalLayout_2.addWidget(self.max_check)
        self.avg_check = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.avg_check.setFont(font)
        self.avg_check.setChecked(True)
        self.avg_check.setObjectName("avg_check")
        self.horizontalLayout_2.addWidget(self.avg_check)
        self.min_check = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.min_check.setFont(font)
        self.min_check.setChecked(True)
        self.min_check.setObjectName("min_check")
        self.horizontalLayout_2.addWidget(self.min_check)
        self.show_more_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.show_more_btn.setFont(font)
        self.show_more_btn.setObjectName("show_more_btn")
        self.horizontalLayout_2.addWidget(self.show_more_btn)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(740, 40, 201, 201))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1029, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.function_label.setText(_translate("MainWindow", "Function: "))
        self.function_name_edit.setText(_translate("MainWindow", "f(x) = "))
        self.population_label.setText(_translate("MainWindow", "Population size:"))
        self.population_label_3.setText(_translate("MainWindow", "Mutation probability:"))
        self.population_label_2.setText(_translate("MainWindow", "Crossing probability:"))
        self.next_step_btn.setText(_translate("MainWindow", "Next step"))
        self.start_auto_btn.setText(_translate("MainWindow", "Start Auto"))
        self.lineEdit_2.setText(_translate("MainWindow", "x^2"))
        self.lineEdit_4.setText(_translate("MainWindow", "x"))
        self.label.setText(_translate("MainWindow", "+"))
        self.label_2.setText(_translate("MainWindow", "+"))
        self.apply_btn.setText(_translate("MainWindow", "Apply"))
        self.clear_btn.setText(_translate("MainWindow", "Stop"))
        self.reset_btn.setText(_translate("MainWindow", "Reset"))
        self.log_label.setText(_translate("MainWindow", "Iteration no. 0"))
        self.max_check.setText(_translate("MainWindow", "Maximum"))
        self.avg_check.setText(_translate("MainWindow", "Average"))
        self.min_check.setText(_translate("MainWindow", "Minimum"))
        self.show_more_btn.setText(_translate("MainWindow", "Show more history"))

