# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(989, 716)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.function_label = QtWidgets.QLabel(self.centralwidget)
        self.function_label.setGeometry(QtCore.QRect(200, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.function_label.setFont(font)
        self.function_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.function_label.setObjectName("function_label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(390, 20, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.function_name_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.function_name_edit.setEnabled(False)
        self.function_name_edit.setGeometry(QtCore.QRect(320, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.function_name_edit.setFont(font)
        self.function_name_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.function_name_edit.setClearButtonEnabled(False)
        self.function_name_edit.setObjectName("function_name_edit")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 80, 351, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.population_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.population_label.setFont(font)
        self.population_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.population_label.setObjectName("population_label")
        self.gridLayout.addWidget(self.population_label, 0, 0, 1, 1)
        self.population_label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.population_label_3.setFont(font)
        self.population_label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.population_label_3.setObjectName("population_label_3")
        self.gridLayout.addWidget(self.population_label_3, 2, 0, 1, 1)
        self.population_label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.population_label_2.setFont(font)
        self.population_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.population_label_2.setObjectName("population_label_2")
        self.gridLayout.addWidget(self.population_label_2, 1, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox.setFont(font)
        self.spinBox.setAccelerated(True)
        self.spinBox.setMaximum(150)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 0, 1, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setAccelerated(True)
        self.doubleSpinBox.setMaximum(1.0)
        self.doubleSpinBox.setSingleStep(0.01)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 1, 1, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox_2.setFont(font)
        self.doubleSpinBox_2.setAccelerated(True)
        self.doubleSpinBox_2.setDecimals(3)
        self.doubleSpinBox_2.setMaximum(1.0)
        self.doubleSpinBox_2.setSingleStep(0.001)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout.addWidget(self.doubleSpinBox_2, 2, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(400, 80, 141, 211))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.start_auto_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.start_auto_btn.setFont(font)
        self.start_auto_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_auto_btn.setStyleSheet("padding: 10px;")
        self.start_auto_btn.setObjectName("start_auto_btn")
        self.gridLayout_2.addWidget(self.start_auto_btn, 0, 0, 1, 1)
        self.next_step_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.next_step_btn.setFont(font)
        self.next_step_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_step_btn.setStyleSheet("padding: 10px;")
        self.next_step_btn.setObjectName("next_step_btn")
        self.gridLayout_2.addWidget(self.next_step_btn, 1, 0, 1, 1)
        self.function_label.raise_()
        self.lineEdit.raise_()
        self.function_name_edit.raise_()
        self.gridLayoutWidget.raise_()
        self.gridLayoutWidget_2.raise_()
        self.next_step_btn.raise_()
        self.next_step_btn.raise_()
        self.start_auto_btn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 989, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.function_label.setText(_translate("MainWindow", "Function: "))
        self.function_name_edit.setText(_translate("MainWindow", "f(x) = "))
        self.population_label.setText(_translate("MainWindow", "Population size:"))
        self.population_label_3.setText(_translate("MainWindow", "Mutation probability:"))
        self.population_label_2.setText(_translate("MainWindow", "Crossing probability:"))
        self.start_auto_btn.setText(_translate("MainWindow", "Start Auto"))
        self.next_step_btn.setText(_translate("MainWindow", "Next step"))

